#!/usr/bin/python3

# Copyright (c) 2020-2022 Stanford University
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# This cperf benchmark compares the performance of Homa with TCP.
# Type "cp_vs_tcp --help" for documentation.

from cperf import *

load_info = [["w2", 3.2], ["w3", 14], ["w4", 20], ["w5", 20]]

parser = get_parser(description=
        'Measures slowdown as a function of message size for Homa and TCP.',
        usage='%(prog)s [options]')
parser.add_argument('--tcp', dest='tcp', type=boolean,
        default=True, help="Boolean value: indicates whether measurements "
                "should be run on TCP (default: true)")
parser.add_argument('--dctcp', dest='dctcp', type=boolean,
        default=False, help="Boolean value:: indicates whether measurements "
                "should be run on DCTCP (default: false)")
parser.add_argument('--servers', dest='num_servers', type=int, metavar='count',
        default=0, help="If nonzero, clients and servers will be segregated "
        "and this value indicates the number of server nodes; all other "
        "nodes will be clients. If 0, each node runs both a client and a "
        "server (default: 0)")
options = parser.parse_args()
init(options)
if options.num_servers <= 0:
    servers = range(0, options.num_nodes)
    clients = range(0, options.num_nodes)
    options.num_clients = options.num_nodes
    options.num_servers = options.num_nodes
    bw_multiplier = 0.5
else:
    if options.num_servers >= options.num_nodes:
        raise Error("Illegal value %d for --servers option; must be less "
                "than --nodes (%d)" % (options.num_servers, options.num_nodes))
    options.num_clients = options.num_nodes - options.num_servers
    servers = range(0, options.num_servers)
    clients = range(options.num_servers, options.num_nodes)
    options.server_ports = options.server_ports * 2
    options.client_ports = options.client_ports * 2
    options.tcp_server_ports = options.tcp_server_ports * 2
    options.tcp_client_ports = options.tcp_client_ports * 2
    bw_multiplier = min(options.num_servers, options.num_clients) \
            / options.num_clients

if options.workload != "":
    load_info = [[options.workload, options.gbps]]

# First, run all of the experiments
if not options.plot_only:
    congestion = get_sysctl_parameter("net.ipv4.tcp_congestion_control")
    for workload, bw in load_info:
        options.workload = workload
        options.gbps = bw * bw_multiplier
        unloaded_exp = "unloaded_" + workload
        homa_exp = "homa_" + workload
        tcp_exp = "tcp_" + workload
        dctcp_exp = "dctcp_" + workload
        try:
            options.protocol = "homa"
            start_servers(range(1, 2), options)

            o = copy.deepcopy(options)
            o.gbps = 0.0
            o.client_ports = 1
            o.client_max = 1
            o.server_ports = 1
            o.server_nodes = 1
            o.first_server = 1
            o.unloaded = 500
            run_experiment(unloaded_exp, range(0, 1), o)

            start_servers(servers, options)
            run_experiment(homa_exp, clients, options)

            if options.tcp:
                options.protocol = "tcp"
                set_sysctl_parameter("net.ipv4.tcp_congestion_control",
                        "cubic", range(0, options.num_nodes))
                start_servers(servers, options)
                run_experiment(tcp_exp, clients, options)

            if options.dctcp:
                options.protocol = "tcp"
                set_sysctl_parameter("net.ipv4.tcp_congestion_control",
                        "dctcp", range(0, options.num_nodes))
                start_servers(servers, options)
                run_experiment(dctcp_exp, clients, options)
        except Exception as e:
            log(traceback.format_exc())

    if options.tcp or options.dctcp:
        print("Resetting TCP congestion control to %s" % (congestion))
        set_sysctl_parameter("net.ipv4.tcp_congestion_control", congestion,
                range(0, options.num_nodes))
    log("Stopping nodes")
    stop_nodes()
    scan_logs()

# Generate plots and reports
experiments = {}
for workload, bw in load_info:
    experiments["unloaded"] = "unloaded_" + workload
    experiments["homa"] = "homa_" + workload
    experiments["tcp"] = "tcp_" + workload
    experiments["dctcp"] = "dctcp_" + workload
    experiments["distbench_homa"] = "distbench_homa_" + workload
    experiments["distbench_grpc"] = "distbench_grpc_" + workload

    set_unloaded(experiments["unloaded"])

    # Generate slowdown plot.
    log("Generating slowdown plot for %s" % (workload))
    title = "%s %d nodes, %.1f Gbps" % (workload.capitalize(),
            options.num_nodes, bw)
    
    ax = start_slowdown_plot(title, 100000000, experiments["homa"])
    for key, value in experiments.items():
        if (key == "unloaded"):
            continue
        plot_slowdown(ax, value, "p99", key + "_p99")
        plot_slowdown(ax, value, "p50", key + "_p50")
    ax.legend(loc="upper right", prop={'size': 5})
    plt.tight_layout()
    plt.savefig("%s/reports/vs_tcp_slowdown%s.pdf" % (options.log_dir, workload))

    ax2 = start_rtt_plot(title, 100000000, experiments["homa"])
    for key, value in experiments.items():
        if (key == "unloaded"):
            continue
        plot_rtts(ax2, value, "p99", key + "_p99")
    ax2.legend(loc="upper right", prop={'size': 5})
    plt.tight_layout()
    plt.savefig("%s/reports/vs_tcp_latencies_p99%s.pdf" % (options.log_dir, workload))

    ax3 = start_rtt_plot(title, 100000, experiments["homa"])
    for key, value in experiments.items():
        if (key == "unloaded"):
            continue
        plot_rtts(ax3, value, "min", key + "_min")
    ax3.legend(loc="upper right", prop={'size': 5})
    plt.tight_layout()
    plt.savefig("%s/reports/vs_tcp_min%s.pdf" % (options.log_dir, workload))

    ax4 = start_rtt_plot(title, 100000, experiments["homa"])
    for key, value in experiments.items():
        if (key == "unloaded"):
            continue
        plot_rtts(ax4, value, "p50", key + "_p50")
    ax4.legend(loc="upper right", prop={'size': 5})
    plt.tight_layout()
    plt.savefig("%s/reports/vs_tcp_latencies_p50%s.pdf" % (options.log_dir, workload))

    # Generate CDF of small-message RTTs.
    log("Generating short message CDF for %s" % (workload))
    start_cdf_plot(title, 10, 10000, 1e-05, "RTT (usecs)",
            "Cumulative Fraction Short Messages")
    for key, value in experiments.items():
        if (key == "unloaded"):
            continue
        x, y = get_short_cdf(value)
        if (x == 0 and y == 0):
            continue
        plt.plot(x, y, label=key)
    unloaded_x, unloaded_y = get_short_cdf(experiments["unloaded"])
    plt.plot(unloaded_x, unloaded_y, label="Homa best case")
    plt.legend(loc="upper right", prop={'size': 9})
    plt.savefig("%s/reports/short_cdf_%s.pdf" % (options.log_dir, workload))
